<?php

/**
 * @file
 * Contains locationentity.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function locationentity_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the locationentity module.
    case 'help.page.locationentity':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function locationentity_theme() {
  $theme = [];
  $theme['locationentity'] = [
    'render element' => 'elements',
    'file' => 'locationentity.page.inc',
    'template' => 'locationentity',
  ];
  $theme['locationentity_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'locationentity.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function locationentity_theme_suggestions_locationentity(array $variables) {
  $suggestions = array();
  $entity = $variables['elements']['#locationentity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'locationentity__' . $sanitized_view_mode;
  $suggestions[] = 'locationentity__' . $entity->bundle();
  $suggestions[] = 'locationentity__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'locationentity__' . $entity->id();
  $suggestions[] = 'locationentity__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
